pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
  displayName: 'yarn install'

- script: |
    yarn lint
  displayName: 'yarn lint'


- script: |
    yarn build
  displayName: 'yarn build'
