pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '9.6.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
  displayName: 'yarn install'

- script: |
    yarn lint
  displayName: 'yarn lint'


- script: |
    yarn build
  displayName: 'yarn build'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'website'
    targetPath: 'dist'